server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: call
          uri: http://localhost:8081
          predicates:
            - Path=/calls/** 
        - id: driving
          uri: http://localhost:8082
          predicates:
            - Path=/drivings/** 
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/** 
        - id: dashboard
          uri: http://localhost:8084
          predicates:
            - Path= /myPayments/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: call
          uri: http://admin11-call:8080
          predicates:
            - Path=/calls/** 
        - id: driving
          uri: http://admin11-driving:8080
          predicates:
            - Path=/drivings/** 
        - id: payment
          uri: http://admin11-payment:8080
          predicates:
            - Path=/payments/** 
        - id: dashboard
          uri: http://admin11-dashboard:8080
          predicates:
            - Path= /myPayments/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
